Add database
Vkurse/-java-filmorate pull request #8
Opened 2023-04-18 13:45 UTC by Vkurse

2023-04-19 14:52 UTC, Fleaman777 requested changes

2023-04-19 14:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +        log.info("Получен запрос на получение MPA по id");
для большей информативности лога можно еще добавить айдишник рейтинга, 

аналагично в жанрах

2023-04-19 14:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (userStorage.getUserById(userId) == null) {
возможно эту проверку лучше сделат то того, как искать фильм, 
тем самым, если юзер не найдется, то не нужно будет лишний раз ходить в базу

2023-04-19 14:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film putALike(int filmId, int userId) {
артикли в названиях можно опустить, т.к. понимание от этого сильно не пострадает, но выглядеть будет чуть компактней

2023-04-19 14:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                .limit(count).collect(Collectors.toList());
стрим лучше воспринимается когда он написан в стрим формате, 
каждый метод стрима на своей строке

2023-04-19 14:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private void userValidation(User user) throws ValidationException {
метод должен начинаться с глагола

2023-04-19 14:52 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> +    }
хороший метод setUp
все необходимое настраивает

2023-04-19 14:52 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> +}
тесты правильные, и выглядят неплохо, 
но так же необходимо добавить тесты на другие публичные методы DbStorage классов

2023-04-21 19:49 UTC, Fleaman777 requested changes

2023-04-21 19:49 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    void shouldCreateAndGetAndUpdateFilm() {
Хороший тест - это тот тест, который проверяет только какой-то один функционал,
Например на обновление,

Так их проще понимать, поддерживать

2023-04-21 19:49 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> +    }
Тесты отличные, 
Но нужно ещё немного добавить:
Для рейтингов и жанров

2023-04-22 10:26 UTC, TyutterinYakov reviewed
Добрый день! В целом - хорошо) Отметил то, что следует исправить :) Хорошего дня! Если возникнут вопросы - пиши в пачку, буду рад помочь🌞

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private Set<Integer> friends;
Коллекция идентификаторов пользователей в друзьях - более не требуется, так как теперь хранение осуществляется в БД)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private Set<Integer> likes;
Аналогично и с коллекцией идентификаторов лайков)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
Для хранения жанров следует использовать `LinkedHashSet`, так как нам важно поддерживать уникальность и сохранять порядок

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Mpa mpa;
Так как фильмов без рейтинга не может быть в нашей системе, над полем следует навесить `@NotNull`

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/GenreService.java
> +    private final GenreDbStorage genreDbStorage;
Внедрение следует произвести через интерфейс класса, так как мы не должны привязываться к конкретной реализации, а работать лишь с предоставляемым API. Также, при использовании интерфейса - будет проще подложить другую реализацию) Например, при смене провайдера БД - текущая реализация может перестать функционировать

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/MpaService.java
> +    private final MpaDbStorage mpaDbStorage;
Внедрение следует произвести через интерфейс класса, так как мы не должны привязываться к конкретной реализации, а работать лишь с предоставляемым API. Также, при использовании интерфейса - будет проще подложить другую реализацию) Например, при смене провайдера БД - текущая реализация может перестать функционировать

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
Эта реализация более не будет использоваться, ее можно исключить)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
Эта реализация более не будет использоваться, ее можно исключить)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +public class MpaDbStorage {
Для класса следует добавить интерфейс) Уточнил в сервисе, где происходит внедрение

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +public class LikeDbStorage {
Для класса следует добавить интерфейс) Уточнил в сервисе, где происходит внедрение

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +public class GenreDbStorage {
Для класса следует добавить интерфейс) Уточнил в сервисе, где происходит внедрение

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/resources/schema.sql
> +);
Можно было бы ввести ограничение на уникальность логина и почты на уровне таблицы в БД)
```
create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);
```

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "SELECT film_id, name, description, release_date, duration, rating_mpa_id " +
MPA следует также присоединить к фильмам в одном SQL запросе, чтобы повторно не производить обращение к БД)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("SELECT film_id, name, description, release_date, duration, rating_mpa_id FROM films");
MPA следует также присоединить к фильмам в одном SQL запросе, чтобы повторно не производить обращение к БД)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film deleteLike(int filmId, int userId) {
Для работы с лайками у нас присутствует отдельный DAO. Действительно ли этот метод должен располагаться здесь?)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film like(int filmId, int userId) {
Для работы с лайками у нас присутствует отдельный DAO. Действительно ли этот метод должен располагаться здесь?)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "SELECT films.*, COUNT(l.film_id) as count FROM films\n" +
MPA следует также присоединить к фильмам в одном SQL запросе, чтобы повторно не производить обращение к БД)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final UserStorage userStorage;
Уровень хранилища не должен зависеть от другого хранилища, либо же от модуля более высокого уровня. Хорошей структурой является та, где модуль верхнего уровня зависит от модуля более низкого уровня, но допускает, когда сервис зависит от другого сервиса

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final MpaDbStorage mpaDbStorage;
Уровень хранилища не должен зависеть от другого хранилища, либо же от модуля более высокого уровня. Хорошей структурой является та, где модуль верхнего уровня зависит от модуля более низкого уровня, но допускает, когда сервис зависит от другого сервиса

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final LikeDbStorage likeDbStorage;
Уровень хранилища не должен зависеть от другого хранилища, либо же от модуля более высокого уровня. Хорошей структурой является та, где модуль верхнего уровня зависит от модуля более низкого уровня, но допускает, когда сервис зависит от другого сервиса

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final GenreDbStorage genreDbStorage;
Уровень хранилища не должен зависеть от другого хранилища, либо же от модуля более высокого уровня. Хорошей структурой является та, где модуль верхнего уровня зависит от модуля более низкого уровня, но допускает, когда сервис зависит от другого сервиса

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        film.getGenres().forEach(g -> {
В данном случае вместо цикла следует использовать `jdbcTemplate.batchUpdate(...`
Так как таким образом мы не будем плодить n-лишние запросы к БД, а сначала соберем все в один пакет и отправим одним запросом)

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.setGenres(genreDbStorage.getGenreForCurrentFilm(film.getId()));
Метод `getGenreForCurrentFilm` следует изменить таким образом, чтобы он принимал коллекцию фильмов, а далее производил извлечение по коллекции идентификаторов необходимые жанры и распределял их по мапе, где ключом будет - идентификатор фильма, а значение - коллекция жанров) Либо же полученную коллекцию фильмов разбить на мапу и при извлечении жанров из ResultSet’a получать идентификатор фильма и по нему производить получение из мапы
`final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));` и добавлять в коллекцию жанров в фильме - новый жанр

О том, как использовать SQL оператор условия `IN` для получение по коллекции идентификаторов - можно посмотреть тут https://www.baeldung.com/spring-jdbctemplate-in-list
Таким образом мы избавимся от n-лишних запросов к БД и улучшим производительность приложения)

Также вызывать этот метод мы будем в сервисе фильмов, а не здесь, так как уровни доступа к данным не должны зависеть друг от друга

Для начала объявляем метод:
```
@Override
public void getGenreForCurrentFilm(List<Film> films) {
...
```

После чего, для того, чтобы производить получение ссылки на объект фильма за О(1), имея лишь его идентификатор, преобразуем полученную коллекцию фильмов к мапе, где ключ - идентификатор, значение - ссылка на объект класса Film
`final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));`
После чего подготавливаем запрос, но перед этим, мы должны отсчитать количество параметров, которое будет передано в условие IN, то есть формируем строку со знаками вопроса в количестве, как размер переданной коллекции фильмов)
`String inSql = String.join(",", Collections.nCopies(films.size(), "?"));`
После этого формирует запрос
`final String sqlQuery = "select * from GENRES g, films_genres fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";`
Итак, время отправлять)
```
		jdbcTemplate.query(sqlQuery, (rs) -> {
//Получили из ResultSet'a идентификатор фильма и извлекли по нему из мапы значение)
			final Film film = filmById.get(rs.getLong("FILM_ID")); 
//Добавили в коллекцию внутри объекта класса FIlm новый жанр)
			film.addGenre(makeGenre(rs, 0));
 //Преобразуем коллекцию типа Film к Integer и в массив, так как передавать требуется именно его
		}, films.stream().map(Film::getId).toArray());
```

После чего, из сервиса фильмов просто передаем коллекцию полученных фильмов из репозитория фильмов)
```
List<Film> films = filmStorage.findAll();
genreStorage.getGenreForCurrentFilm(films);
return film;
```

При получении одного фильма, можно его упаковать с помощью метода of из List)
```
Film film = filmStorage.findById(id);
genreStorage.getGenreForCurrentFilm(List.of(film));
return film;
```

2023-04-22 10:26 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private void validationUser(User user) throws ValidationException {
Метод должен находиться на уровне сервиса и вызываться там же, так как это часть бизнес-правил
Также действительно ли требуется указывать в заголовке `ValidationException`?)

2023-04-22 15:46 UTC, Vkurse commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private Set<Integer> friends;
Можно я оставлю возможность хранения inMemori и из удаления этой функции хранения не буду перелопачивать весь проект за день до хард дедлайна? Насколько я понял задачи удалить старую версию в текущем спринте не было

2023-04-23 18:06 UTC, TyutterinYakov approved these changes
Добрый вечер! Да, хорошо, я приму работу, так как твой ревьюер в отпуске. В будущем эти замечания можешь подправить) Хорошего вечера и отличного настроения!🥳 Желаю интересной и продуктивной работы над групповым проектом!)

2023-04-23 18:12 UTC, merged